const {pathToFileURL}=require('node:url'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
let playwright;
try{playwright=require(process.env.EXAMINER_PLAYWRIGHT_PATH||'playwright')}catch(error){if(process.env.EXAMINER_PLAYWRIGHT_PATH)throw error;playwright=require(path.join(os.homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'))}
const {chromium}=playwright;
const root=path.join(__dirname,'..'),base=pathToFileURL(path.join(root,'examiner-test/index.html')).href,hub=pathToFileURL(path.join(root,'오답_훈련센터.html')).href;
const out=process.env.EXAMINER_ARTIFACT_DIR||path.join(root,'examiner-test/artifacts');fs.mkdirSync(out,{recursive:true});
const key='exam-20260914-examiner-test-v1',coreKeys=['exam-20260914-theory','exam-20260914-practical','exam-20260914-voucher'];
(async()=>{
  const executablePath=process.env.EXAMINER_BROWSER_PATH||(process.platform==='win32'?path.join(process.env['ProgramFiles(x86)']||'C:/Program Files (x86)','Microsoft/Edge/Application/msedge.exe'):undefined);
  const browser=await chromium.launch({executablePath,headless:true});
  try{
    const context=await browser.newContext({viewport:{width:1280,height:900}}),page=await context.newPage(),errors=[],requests=[];
    page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));await context.route('https://**/*',route=>route.abort());
    await context.addInitScript(({coreKeys})=>{for(const k of coreKeys)if(localStorage.getItem(k)===null)localStorage.setItem(k,JSON.stringify({sentinel:k,history:[{id:'keep-record',correct:true,cancelledAt:'2026-10-04'}]}))},{coreKeys});
    await page.goto(base);assert.equal(await page.locator('#mode').isHidden(),true);assert.ok(!requests.some(r=>r.includes('/analysis.js')||r.includes('/questions.js')));
    const before=await page.evaluate(keys=>Object.fromEntries(keys.map(k=>[k,localStorage.getItem(k)])),coreKeys);
    await page.locator('#start-mode').click();await page.locator('#mode').waitFor({state:'visible'});assert.ok(requests.some(r=>r.includes('/analysis.js')));
    await page.locator('#open-trial').click();assert.equal(await page.locator('.question').count(),6);
    const answer=await page.evaluate(()=>window.ExaminerPilot.questions.find(q=>q.id===document.querySelector('.question').dataset.id).answer),card=page.locator('.question').first();
    await card.locator(`input[value="${answer}"]`).check();await card.locator('.grade').click();assert.match(await card.locator('.grade-result').innerText(),/정답/);assert.equal(await card.locator('.answer').evaluate(d=>d.open),true);
    await card.locator('.quality summary').click();await card.locator('[data-rating=sentence]').selectOption('2');await card.locator('[data-rating=surprise]').selectOption('1');await card.locator('.quality-note').fill('문장은 자연스럽고 계산을 늘리지 않았음');await card.locator('.save-quality').click();
    assert.equal(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).attempts.length,key),1);assert.equal(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).evaluations.length,key),1);
    await page.locator('#make-request').click();assert.match(await page.locator('#request-text').inputValue(),/5회분|5회/);assert.ok((await page.locator('#request-text').inputValue()).length<30000);
    const snapshot=await page.evaluate(key=>localStorage.getItem(key),key);await page.reload();await page.locator('#start-mode').click();await page.locator('.question').first().waitFor();assert.match(await page.locator('.grade-result').first().innerText(),/정답/);assert.equal(await page.evaluate(key=>localStorage.getItem(key),key),snapshot);
    // No implicit approval, and imported text is rendered inert rather than as HTML.
    const incoming=await page.evaluate(()=>{const p=JSON.parse(JSON.stringify(window.ExaminerPilot));p.id='import-one';p.label='가져온 묶음';p.questions=p.questions.slice(0,1);p.questions[0].id='import-question';p.questions[0].title='<img src=x onerror="window.injection=1">';return p});
    await page.locator('#import-text').evaluate(el=>el.closest('details').open=true);await page.locator('#import-text').fill(JSON.stringify(incoming));await page.locator('#stage-import').click();assert.equal(await page.locator('#approve-import').isDisabled(),true);assert.equal(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).packs.length,key),0);assert.equal(await page.locator('#pending img').count(),0);
    await page.locator('#review-confirm').check();await page.locator('#approve-import').click();assert.equal(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).packs.length,key),1);await page.locator('#open-trial').click();assert.equal(await page.locator('.question').count(),1);assert.equal(await page.locator('.question img').count(),0);
    const downloadPromise=page.waitForEvent('download');await page.locator('#export-state').click();const download=await downloadPromise;assert.match(download.suggestedFilename(),/출제위원/);const saved=await download.path();await page.locator('#restore-state').setInputFiles(saved);await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('합쳤'));assert.match(await page.locator('#status').innerText(),/합쳤/);
    const existing=await page.evaluate(key=>localStorage.getItem(key),key);const foreign={schemaVersion:1,season:'old',packs:[],trials:[],attempts:[],evaluations:[]};await page.locator('#restore-state').setInputFiles({name:'wrong.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(foreign))});await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('중단'));assert.match(await page.locator('#status').innerText(),/중단/);assert.equal(await page.evaluate(key=>localStorage.getItem(key),key),existing);
    assert.deepEqual(await page.evaluate(keys=>Object.fromEntries(keys.map(k=>[k,localStorage.getItem(k)])),coreKeys),before);
    // Selecting a style with one eligible question never duplicates it to reach six.
    await page.locator('#pack-select').selectOption('committee-pilot-20261005');for(const box of await page.locator('#style-options input').all())await box.uncheck();await page.locator('#style-options input[value="예외규정"]').check();await page.locator('#open-trial').click();assert.equal(await page.locator('.question').count(),1);
    await page.locator('.answer summary').click();await page.locator('summary').filter({hasText:'출제 의도'}).first().click();await page.locator('.question').first().evaluate(el=>el.scrollIntoView({block:'start'}));await page.screenshot({path:out+'/examiner-desktop.png',fullPage:false});
    // Existing home can reach the test without requesting the analysis files itself.
    requests.length=0;await page.goto(hub);assert.equal(await page.locator('a[href="examiner-test/index.html"]').count(),1);assert.ok(!requests.some(r=>r.includes('/examiner-test/analysis')||r.includes('/examiner-test/questions')));
    // Protect corrupt records and failed writes, never replace them with an empty state.
    await page.goto(base);await page.evaluate(key=>localStorage.setItem(key,'{bad-json'),key);await page.locator('#start-mode').click();await page.locator('#mode').waitFor({state:'visible'});await page.locator('#open-trial').click();assert.match(await page.locator('#status').innerText(),/보존|복구/);assert.equal(await page.evaluate(key=>localStorage.getItem(key),key),'{bad-json');
    await page.evaluate(key=>localStorage.removeItem(key),key);await page.reload();await page.locator('#start-mode').click();await page.locator('#mode').waitFor({state:'visible'});await page.evaluate(key=>{const set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k===key)throw Error('quota exceeded');return set.call(this,k,v)}},key);await page.locator('#open-trial').click();assert.match(await page.locator('#status').innerText(),/저장하지 못/);assert.equal(await page.locator('.question').count(),0);
    const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),phone=await mobile.newPage();await mobile.route('https://**/*',route=>route.abort());phone.on('pageerror',e=>errors.push(e.message));await phone.goto(base);await phone.locator('#start-mode').click();await phone.locator('#mode').waitFor({state:'visible'});await phone.locator('#open-trial').click();assert.equal(await phone.locator('.question').count(),6);assert.ok(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
    const receipt=phone.locator('.question').filter({has:phone.locator('table')}).first();await receipt.evaluate(el=>el.scrollIntoView({block:'start'}));assert.ok(await receipt.locator('.table-wrap').evaluate(e=>e.scrollWidth<=e.clientWidth+1),'small question tables fit mobile without losing their right column');assert.ok(await phone.locator('#concept-rows').evaluate(e=>e.closest('.table-wrap').scrollWidth>e.closest('.table-wrap').clientWidth),'wide analysis table stays in a labelled scroll container');await phone.screenshot({path:out+'/examiner-mobile.png',fullPage:false});assert.deepEqual(errors,[]);
    console.log('PASS: lazy mode, six questions, grading, quality/history preservation, manual import gate, inert HTML, backup merge, old-season rejection, main-state isolation, style filtering, corrupt/quota protection, home link and 390px mobile layout');
    await mobile.close();await context.close();
  }finally{await browser.close()}
})().catch(error=>{console.error(error);process.exit(1)});
